# Default Configuration for Medical Image Analysis

# Data Configuration
data:
  data_dir: "data"
  metadata_file: "archive/overview.csv"
  image_size: [256, 256]
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  batch_size: 16
  num_workers: 4

# Model Configuration
model:
  architecture: "unet"  # Options: unet, deeplabv3
  in_channels: 1
  num_classes: 2  # For classification: contrast vs no-contrast
  depth: 4
  start_filters: 64
  dropout: 0.2

# Training Configuration
training:
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 1e-4
  optimizer: "adam"  # Options: adam, sgd, adamw
  scheduler: "reduce_on_plateau"  # Options: reduce_on_plateau, cosine, step
  early_stopping_patience: 10
  gradient_accumulation_steps: 1
  mixed_precision: true

# Loss Configuration
loss:
  classification_loss: "cross_entropy"
  segmentation_loss: "dice"
  loss_weights:
    classification: 1.0
    segmentation: 1.0

# Augmentation Configuration
augmentation:
  enabled: true
  rotation_limit: 15
  brightness_limit: 0.2
  contrast_limit: 0.2
  horizontal_flip: true
  vertical_flip: false
  gaussian_noise: 0.01

# Evaluation Configuration
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "dice_coefficient"
    - "iou"
  save_predictions: true
  save_visualizations: true

# Paths Configuration
paths:
  output_dir: "outputs"
  checkpoint_dir: "outputs/checkpoints"
  predictions_dir: "outputs/predictions"
  logs_dir: "outputs/logs"
  
# Device Configuration
device:
  use_cuda: true
  device_id: 0